// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaTPAfedbt6AeLQdN5YK56EIIOP4jAZZs',
    appId: '1:648316138738:web:5687d1836e7ea1f047cc6b',
    messagingSenderId: '648316138738',
    projectId: 'stor-miac',
    authDomain: 'stor-miac.firebaseapp.com',
    storageBucket: 'stor-miac.firebasestorage.app',
    measurementId: 'G-8VZ91TS40Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6emJWE-I1_Q9tLvCsjGsp3yPgMbcdnMs',
    appId: '1:648316138738:android:8f57bf0f47c69da747cc6b',
    messagingSenderId: '648316138738',
    projectId: 'stor-miac',
    storageBucket: 'stor-miac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChv_QPmFmd3aUwoAfGmTegeG8KUhW9qho',
    appId: '1:648316138738:ios:9d4fbfc27e48023f47cc6b',
    messagingSenderId: '648316138738',
    projectId: 'stor-miac',
    storageBucket: 'stor-miac.firebasestorage.app',
    iosBundleId: 'com.example.storeMiac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChv_QPmFmd3aUwoAfGmTegeG8KUhW9qho',
    appId: '1:648316138738:ios:9d4fbfc27e48023f47cc6b',
    messagingSenderId: '648316138738',
    projectId: 'stor-miac',
    storageBucket: 'stor-miac.firebasestorage.app',
    iosBundleId: 'com.example.storeMiac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaTPAfedbt6AeLQdN5YK56EIIOP4jAZZs',
    appId: '1:648316138738:web:0a0aae0c1603b3ed47cc6b',
    messagingSenderId: '648316138738',
    projectId: 'stor-miac',
    authDomain: 'stor-miac.firebaseapp.com',
    storageBucket: 'stor-miac.firebasestorage.app',
    measurementId: 'G-YNYX2F3PBX',
  );
}
